GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Moe",
    "password": "admin"
}


###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1vZSIsInBhc3N3b3JkIjoiJDJiJDEwJFduQU1KNlZydXhPR2hLdEo2bUJERGV4MTdkU3pTY1RKODRaTThJNjRCZGJTVTgyRFVhRzFpIiwiaWF0IjoxNjg5Njc2Njk2fQ.ukdU2matY3iIuJfo0sTcB8jvejozxCViVguYXXNhsvs"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Moe",
    "password": "admin"
}


###

GET http://localhost:3000/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1vZSIsImlhdCI6MTY4OTY3NjgyNSwiZXhwIjoxNjg5Njc2ODQwfQ.ONe3WDzKHtj5OIA0x3FO18wZ8jtoQpcy99YNvhy7iho